### ISSUE TITLE
This seemingly is not working. The assignments are not sorted

### ISSUE THREAD

**Issue by hbiede** [cbourke/ComputerScienceI#9]
https://github.com/cbourke/ComputerScienceI/blob/69349fe7f70bd865b46e877f055636da743c3d2f/scripts/php/assignGraders.php#L120

**Comment by cbourke** [comment]
These scripts were used in F18; we're using the python scripts for codepost.io now.  

Is it necessary to sort by grader and/or by student for a grader?

**Comment by hbiede** [comment]
While not necessary, it would be more convenient if you could sort by last name for the purposes of using SpeedGrader

**Comment by cbourke** [comment]
I've modified the python scripts to do this: 670ed26 but I still don't see why it would help with canvas.  Now that all comments are in codepost, graders do not enter anything into canvas other than the final grade.  It is easier to do this in the gradebook where you can use a quick filter instead of speed grader.

**Comment by hbiede** [comment]
True. I guess I’m stuck in my old ways since my grading has been limited since the CodePost transition.
